# batch_size: 32768
batch_size: 1024
fast_dev_run: false
max_epochs: 500
min_epochs: 1
max_time: null
accelerator: auto
devices: -1
accumulate_grad_batches: 1
auto_lr_find: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 50
checkpoints: valid_loss
checkpoints_path: ""
checkpoints_every_n_epochs: 1
checkpoints_mode: min
checkpoints_save_top_k: 1
load_best: true
track_grad_norm: -1
progress_bar: none
seed: 1337
